apiVersion: v1
kind: Service
metadata:
  name: test-namespace
  namespace: test-namespace
  labels:
    app: test-namespace
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: test-namespace
